### ISSUE TITLE
session-leak, after error when registering tx-synchronization

### ISSUE THREAD

**Issue by apinske** [messaginghub/pooled-jms#35]
When an error occurs during the registering of the tx-sync in PooledXAConnection.createSession, the session is not put back in the pool and leaks.

Caused by: javax.transaction.RollbackException: ARJUNA016083: Cannot register synchronization because the transaction is in aborted state
	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.registerSynchronizationImple(TransactionImple.java:395)
	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.registerSynchronization(TransactionImple.java:376)
	at org.messaginghub.pooled.jms.pool.PooledXAConnection.createSession(PooledXAConnection.java:70)

Find a small sample project: https://github.com/apinske/playground-mq/tree/narayana-leak

**Comment by tabish121** [comment]
Fixed as part of #32

**Comment by apinske** [comment]
Will there be a 1.2.7 release with this fix?

**Comment by tabish121** [comment]
I don't currently have plans to release any more 1.x series versions as you can use 2.x with clients still on the javax.jms versions of JMS clients

**Comment by tabish121** [comment]
I've released v1.2.7 with this fix merged in
